-- Provide SQL scripts here
create table person (
    id bigint generated by default as identity,
    p_state varchar(2),
    p_email varchar(255) not null,
    p_name varchar(255) not null,
    p_nickname varchar(255),
    p_password varchar(255) not null,
    primary key (id),
    constraint person_email_uni unique (p_email)
)